locales_dict = {
    "en":    {"flag": "GB", "name": "English"},
    "ar":    {"flag": "SA", "name": "اَلْعَرَبِيَّةُ"},
    "be":    {"flag": "BY", "name": "Беларуская мова"},
    "bg":    {"flag": "BG", "name": "Български"},
    "ca":    {"flag": "AD", "name": "Català"},
    "cs":    {"flag": "CZ", "name": "Česky"},
    "da":    {"flag": "DK", "name": "Dansk"},
    "de":    {"flag": "DE", "name": "Deutsch"},
    "el":    {"flag": "GR", "name": "Ελληνικά"},
    "es":    {"flag": "ES", "name": "Español"},
    "fi":    {"flag": "FI", "name": "Suomi"},
    "fil":   {"flag": "PH", "name": "Wikang Filipino"},
    "fr":    {"flag": "FR", "name": "Français"},
    "he":    {"flag": "IL", "name": "עִבְרִית"},
    "hu":    {"flag": "HU", "name": "Magyar"},
    "id":    {"flag": "ID", "name": "Bahasa Indonesia"},
    "it":    {"flag": "IT", "name": "Italiano"},
    "ja":    {"flag": "JP", "name": "日本語"},
    "ko":    {"flag": "KR", "name": "한국어"},
    "lt":    {"flag": "LT", "name": "Lietuvių kalba"},
    "nl":    {"flag": "NL", "name": "Nederlands"},
    "no":    {"flag": "NO", "name": "Norsk"},
    "pl":    {"flag": "PL", "name": "Polski"},
    "pt":    {"flag": "PT", "name": "Português"},
    "pt-br": {"flag": "BR", "name": "Português brasileiro"},
    "ro":    {"flag": "RO", "name": "Română"},
    "ru":    {"flag": "RU", "name": "Русский"},
    "sk":    {"flag": "SK", "name": "Slovenčina"},
    "sl":    {"flag": "SI", "name": "Slovenščina"},
    "sr":    {"flag": "RS", "name": "Српски"},
    "sv":    {"flag": "SE", "name": "Svenska"},
    "th":    {"flag": "TH", "name": "ไทย"},
    "tr":    {"flag": "TR", "name": "Türkçe"},
    "uk":    {"flag": "UA", "name": "Українська мова"},
    "vi":    {"flag": "VN", "name": "Tiếng Việt"},
    "zh":    {"flag": "CN", "name": "简体中文"},
    "zh-tw": {"flag": "TW", "name": "繁體中文（台灣）"},
}
